site_name: KubeADMIN docs
pages:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Contributing: contributing.md
  - Changelog: changelog.md
  - Issues: issues.md
theme: readthedocs
