site_name: KubeADMIN docs
pages:
  - Home: index.md
  - Install:
    - 'Prerequisites': install/prerequisites.md
    - 'Installation': install/installation.md
    - 'Upgrade': install/upgrade.md
  - Contributing: contributing.md
  - Changelog: changelog.md
theme: readthedocs
