etcd:
  image: quay.io/coreos/etcd:v2.2.5
  net: host

master:
  image: holandes22/hyperkube:v1.1.8-cors
  net: host
  pid: host
  privileged: true
  volumes:
    - /:/rootfs:ro
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
    - /var/lib/kubelet/:/var/lib/kubelet:rw
    - /var/run:/var/run:rw
  command: /hyperkube kubelet --containerized --hostname-override="127.0.0.1" --address="0.0.0.0" --api-servers=http://localhost:8080 --config=/etc/kubernetes/manifests --host-network-sources="*"

proxy:
  image: gcr.io/google_containers/hyperkube:v1.1.8
  net: host
  privileged: true
  command: /hyperkube proxy --master=http://127.0.0.1:8080 --v=2
